name: checkmen_app
description: Um novo projeto Flutter para o CheckMen.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.10
  flutter_html: ^3.0.0-beta.2
  intl: 0.20.2 
  collection: ^1.18.0 
  google_generative_ai: ^0.4.7 
  flutter_markdown: ^0.7.0

  # ðŸŸ¢ NOVO: Adicionar Firebase
  firebase_core: ^2.27.1  
  firebase_messaging: ^14.8.4 
  
  # ðŸŸ¢ CORREÃ‡ÃƒO: Adicionar NotificaÃ§Ãµes Locais (necessÃ¡rio para o erro anterior)
  flutter_local_notifications: ^17.0.0

  # DependÃªncias do Hive para salvar dados
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  analyzer: 6.4.1
  # DependÃªncias de desenvolvimento para Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/generative_ai_key.txt

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoapp.png"
  min_sdk_android: 21